name: testdriveviets
favicon: null
layout_spectrum: 0.9920523490291089
typography_spectrum: 0.74209
title: testdriveviets
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3099413795862347
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
